import os
from dotenv import load_dotenv
from pymongo import MongoClient

# Load environment variables from .env file
load_dotenv()

# Get values from the .env file
MONGO_URI = os.getenv("MONGO_URI")

# MongoDB connection
client = MongoClient(MONGO_URI)
db = client.food_app
food_collection = db.foods
# Delete all existing documents
food_collection.delete_many({})

# Dummy food data with the same image for all foods
food_data = [
    {
        "name": "Rice Plate Aaisaheb",
        "location": "https://maps.app.goo.gl/UGqcY1ocJHVq1EkRA",
        "hotelname": "Aaisaheb Mess",
        "type": "Rice Plate",
        "rating": 4.5,
        "price": 80,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "aaisaheb.jpg", 
        "landmark": "Mess Gully",
        "veg": True,
        "otheroptions": ["Various types of Maharashtrian foods"]
    },
    {
        "name": "Rice Plate Maitri Katta",
        "location": "https://maps.app.goo.gl/RNBrdZvUgWT7f6QA6",
        "hotelname": "Maitri Katta Mess",
        "type": "Rice Plate",
        "rating": 4.5,
        "price": 80,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "maitrikatta.jpg", 
        "landmark": "Mess Gully",
        "veg": True,
        "otheroptions": ["Various types of Maharashtrian foods"]
    },
    {
        "name": "Rice Plate Tuljabhavani",
        "location": "https://maps.app.goo.gl/DVu2QAB5pxZxR5fW7",
        "hotelname": "Tuljabhavani Mess",
        "type": "Rice Plate",
        "rating": 4.5,
        "price": 80,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "image.jpg",  
        "landmark": "Mess Gully",
        "veg": True,
        "otheroptions": ["Various types of Maharashtrian foods"]
    },
    {
        "name": "Misal PM",
        "location": "https://maps.app.goo.gl/nF53Jh9QE2NXD4dg6",
        "hotelname": "PM Misal",
        "type": "Misal",
        "rating": 4.5,
        "price": 80,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "pm.jpg", 
        "landmark": "Akurdi Railway Station",
        "veg": True,
        "otheroptions": ["Misal and Bhel"]
    },
    {
        "name": "Samosa Chaat",
        "location": "https://maps.app.goo.gl/MydWTqRE3VXhPimC6",
        "hotelname": "Krushnai Snacks",
        "type": "Chaat",
        "rating": 4.5,
        "price": 50,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "krushnai.png",  
        "landmark": "Akurdi Railway Station",
        "veg": True,
        "otheroptions": ["Pohe, Dal Pakwan"]
    },
    {
        "name": "Dalcha Rice 7 Mitranchi",
        "location": "https://maps.app.goo.gl/MydWTqRE3VXhPimC6",
        "hotelname": "7 Mitranchi Dalcha Rice",
        "type": "Rice",
        "rating": 4.5,
        "price": 20,
        "quantity": 2,
        "time": "All Day",
        "imageurl": "image.jpg",  
        "landmark": "Akurdi Railway Station",
        "veg": True,
        "otheroptions": ["Nilanga Rice"]
    },
    {
        "name": "Maharashtra Chinese",
        "location": "https://maps.app.goo.gl/vQXqWYLiWNtwaTpSA",
        "hotelname": "Maharashtra Hotel",
        "type": "Chinese",
        "rating": 4.5,
        "price": 100,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "maharashtra.jpg",  
        "landmark": "Akurdi Railway Station",
        "veg": False,
        "otheroptions": ["Various Chinese Dishes"]
    },
    {
        "name": "Maharashtra Biryani",
        "location": "https://maps.app.goo.gl/vQXqWYLiWNtwaTpSA",
        "hotelname": "Maharashtra Hotel",
        "type": "Biryani",
        "rating": 4.5,
        "price": 120,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "maharashtra.jpg",  
        "landmark": "Akurdi Railway Station",
        "veg": False,
        "otheroptions": ["Veg Biryani"]
    },
    {
        "name": "Shawarma",
        "location": "https://maps.app.goo.gl/tYXA8HAHtsL9GnXm6",
        "hotelname": "Shawarma King",
        "type": "Shwarma",
        "rating": 4.5,
        "price": 150,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "shwarma.jpg",  
        "landmark": "Akurdi Railway Station",
        "veg": False,
        "otheroptions": ["Various Types of Shawarmas"]
    },
    {
        "name": "Medu Wada Gangotree",
        "location": "https://maps.app.goo.gl/bxwvVCWqfnuiCvHw9",
        "hotelname": "Gangotree Fast Food",
        "type": "South Indian",
        "rating": 4.5,
        "price": 70,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "gangotree.jpg",  
        "landmark": "Akurdi Railway Station",
        "veg": True,
        "otheroptions": ["Idli, Dosa"]
    },
    {
        "name": "Veg Biryani Gangotree",
        "location": "https://maps.app.goo.gl/bxwvVCWqfnuiCvHw9",
        "hotelname": "Gangotree Fast Food",
        "type": "Biryani",
        "rating": 4.5,
        "price": 70,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "gangotree.jpg",  
        "landmark": "Akurdi Railway Station",
        "veg": True,
        "otheroptions": ["Various Maharashtraian Dishes"]
    },
    {
        "name": "Rice Plate Gangotree",
        "location": "https://maps.app.goo.gl/bxwvVCWqfnuiCvHw9",
        "hotelname": "Gangotree Fast Food",
        "type": "Rice Plate",
        "rating": 4.5,
        "price": 100,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "gangotree.jpg",  
        "landmark": "Akurdi Railway Station",
        "veg": True,
        "otheroptions": ["Various Maharashtraian Dishes"]
    },
    {
        "name": "Gaarva Chicken Biryani",
        "location": "https://maps.app.goo.gl/FQVJg86cRFfzmsBd6",
        "hotelname": "Gaarva Biryani",
        "type": "Biryani",
        "rating": 4.5,
        "price": 100,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "biryani.jpeg",  
        "landmark": "Gurudwara Chowk",
        "veg": False,
        "otheroptions": ["Various types of biryani"]
    },
    {
        "name": "Misal Paav CSK",
        "location": "https://maps.app.goo.gl/FQVJg86cRFfzmsBd6",
        "hotelname": "CSK",
        "type": "Misal",
        "rating": 4.5,
        "price": 70,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "csk.jpg",  
        "landmark": "PCCOE",
        "veg": True,
        "otheroptions": ["Various types of Foods"]
    },
    {
        "name": "Noodles CSK",
        "location": "https://maps.app.goo.gl/FQVJg86cRFfzmsBd6",
        "hotelname": "CSK",
        "type": "Misal",
        "rating": 4.5,
        "price": 70,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "csk.jpg",  
        "landmark": "PCCOE",
        "veg": True,
        "otheroptions": ["Various types of Foods"]
    },
    
    {   "name": "Medu Vada CSK",
        "location": "https://maps.app.goo.gl/a3aBg76Sk9DcNDQX8",
        "hotelname": "CSK",
        "type": "South Indian",
        "rating": 4.5,
        "price": 40,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "csk.jpg",  
        "landmark": "PCCOE",
        "veg": True,
        "otheroptions": ["Various types of Foods South Indian"]
    },

    {   "name": "Idli CSK",
        "location": "https://maps.app.goo.gl/a3aBg76Sk9DcNDQX8",
        "hotelname": "CSK",
        "type": "South Indian",
        "rating": 4.5,
        "price": 50,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "csk.jpg",  
        "landmark": "PCCOE",
        "veg": True,
        "otheroptions": ["Various types of Foods South Indian"]
    },

    {   "name": "Rice Plate CSK",
        "location": "https://maps.app.goo.gl/a3aBg76Sk9DcNDQX8",
        "hotelname": "CSK",
        "type": "Rice Plate",
        "rating": 4.5,
        "price": 80,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "csk.jpg", 
        "landmark": "PCCOE",
        "veg": True,
        "otheroptions": ["Various types of Maharashtrian Foods"]
    },

    {   "name": "Rice Plate Morya",
        "location": "https://maps.app.goo.gl/TPPF3pjZWyantBgj9",
        "hotelname": "Morya",
        "type": "Rice Plate",
        "rating": 4.5,
        "price": 80,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "morya.jpeg", 
        "landmark": "PCCOE",
        "veg": True,
        "otheroptions": ["Various types of Maharashtrian Foods"]
    }, 

    {   "name": "Vada Pav Morya",
        "location": "https://maps.app.goo.gl/TPPF3pjZWyantBgj9",
        "hotelname": "Morya",
        "type": "Vada Pav",
        "rating": 4.5,
        "price": 15,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "morya.jpeg", 
        "landmark": "PCCOE",
        "veg": True,
        "otheroptions": ["Various types of Maharashtrian Foods"]
    },


    {   "name": "Rice Plate Savi",
        "location": "https://maps.app.goo.gl/YEt2vjiKYGBupirp7",
        "hotelname": "Savi Mess",
        "type": "Rice Plate",
        "rating": 4.5,
        "price": 80,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "savi.jpg", 
        "landmark": "PCCOE",
        "veg": True,
        "otheroptions": ["Various types of Maharashtrian Foods"]
    },

    {   "name": "Veg Burger SK",
        "location": "https://maps.app.goo.gl/NruKLr7133EWzg198",
        "hotelname": "SK's Crown Burger ",
        "type": "Burger",
        "rating": 4.5,
        "price": 110,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "sk.jpg", 
        "landmark": "PCCOE",
        "veg": True,
        "otheroptions": ["Various types of Burgers"]
    },

    {   "name": "Chicken Burger SK",
        "location": "https://maps.app.goo.gl/NruKLr7133EWzg198",
        "hotelname": "SK's Crown Burger ",
        "type": "Burger",
        "rating": 4.5,
        "price": 160,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "sk.jpg", 
        "landmark": "PCCOE",
        "veg": False,
        "otheroptions": ["Various types of Burgers"]
    },

    {   "name": "Samosa city",
        "location": "https://maps.app.goo.gl/zcpWBmA3ZsXL3obP6",
        "hotelname": "City Samosa ",
        "type": "Samosa",
        "rating": 4.5,
        "price": 18,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "city.jpg", 
        "landmark": "Dharmaraj Chowk",
        "veg": True,
        "otheroptions": ["Various types of Samosa"]
    },

    {   "name": "Rice Plate Mahalaxmi",
        "location": "https://maps.app.goo.gl/DkiynykftnL1NF9F9",
        "hotelname": "Shree Mahalaxmi Mess",
        "type": "Rice Plate",
        "rating": 4.5,
        "price": 80,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "laxmi.jpg", 
        "landmark": "Dharmaraj Chowk",
        "veg": True,
        "otheroptions": ["Various types of Maharashtrian Foods"]
    },

    {   "name": "Hyderabadi Veg Biryani ",
        "location": "https://maps.app.goo.gl/rrZGshE7wo3DYw8p8",
        "hotelname": "Hyderabadi Jayka Biryani",
        "type": "Biryani",
        "rating": 4.5,
        "price": 140,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "biryani.jpeg", 
        "landmark": "Dharmaraj Chowk",
        "veg": True,
        "otheroptions": ["Various types of Biryani"]
    },

    {   "name": "Hyderabadi Jayka Chicken Biryani ",
        "location": "https://maps.app.goo.gl/rrZGshE7wo3DYw8p8",
        "hotelname": "Hyderabadi Jayka Biryani",
        "type": "Biryani",
        "rating": 4.5,
        "price": 140,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "biryani.jpeg", 
        "landmark": "Dharmaraj Chowk",
        "veg": False,
        "otheroptions": ["Various types of Biryani"]
    },

    {   "name": " Chicken Roll",
        "location": "https://maps.app.goo.gl/sFXyXxRsZRdy7uaJ9",
        "hotelname": "Shrirang Rock & Roll",
        "type": "Role",
        "rating": 4.5,
        "price": 20,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "chickenroll.jpeg", 
        "landmark": "Dharmaraj Chowk",
        "veg": False,
        "otheroptions": ["Various types of rolls"]
    },

    {   "name": "Thick Coffee",
        "location": "https://maps.app.goo.gl/V31a23Si5ZpVGnGy5",
        "hotelname": "Coffee",
        "type": "Role",
        "rating": 4.5,
        "price": 30,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "cc.jpeg", 
        "landmark": "Dharmaraj Chowk",
        "veg": True,
        "otheroptions": ["Various types of cold drinks"]
    },

    {   "name": "Rice Plate Shreyas",
        "location": "https://maps.app.goo.gl/nuFK4TrcRJHBMyFMA",
        "hotelname": "Hotel Shreyas",
        "type": "Rice Plate",
        "rating": 4.5,
        "price": 70,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "shreyas.jpg", 
        "landmark": "Dharmaraj Chowk",
        "veg": True,
        "otheroptions": ["Various types of Maharashtrian Foods"]
    },


    {   "name": "Dosa Dakshin",
        "location": "https://maps.app.goo.gl/7LXuvSwFPuroqNPy6",
        "hotelname": "Dakshin Dosa",
        "type": "Dosa",
        "rating": 4.5,
        "price": 60,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "dosa.jpeg", 
        "landmark": "Dharmaraj Chowk",
        "veg": True,
        "otheroptions": ["Various types of South Indian Food"]
    },

    {   "name": "Misal Shindeshahi",
        "location": "https://maps.app.goo.gl/xdAqN2A8NQ1SX7Cz6",
        "hotelname": "Shindeshahi Amruttulya",
        "type": "Misal",
        "rating": 4.5,
        "price": 60,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "shindeshahi.jpg", 
        "landmark": "Dharmaraj Chowk",
        "veg": True,
        "otheroptions": ["Various types of Food"]
    },

    {   "name": "Laziz Chicken Biryani",
        "location": "https://maps.app.goo.gl/WbngdNj7pRXwiofr7",
        "hotelname": " Laziz Biryani",
        "type": "Biryani",
        "rating": 4.5,
        "price": 120,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "biryani.jpeg", 
        "landmark": "Dharmaraj Chowk",
        "veg": False,
        "otheroptions": ["Various types of Biryani"]
    },

    {   "name": "Fruit Juice",
        "location": "https://maps.app.goo.gl/WbngdNj7pRXwiofr7",
        "hotelname": "Shivam Juice",
        "type": "Juice",
        "rating": 4.5,
        "price": 50,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "juice.jpg", 
        "landmark": "Maa Vaishino Devi Dham",
        "veg": True,
        "otheroptions": ["Various types of Juice"]
    },

    {   "name": "Dal Bati Sugam",
        "location": "https://maps.app.goo.gl/1NN9Gs1N22pF5tZK7",
        "hotelname": "Sugam Pure Veg Dining",
        "type": "Dal Bati",
        "rating": 4.5,
        "price": 90,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "dalbati.jpeg", 
        "landmark": "Maa Vaishino Devi Dham",
        "veg": True,
        "otheroptions": ["Various types of rajasthani Food"]
    },

    {   "name": "Rice Plate Sarovar",
        "location": "https://maps.app.goo.gl/1NN9Gs1N22pF5tZK7 ",
        "hotelname": "Sarovar",
        "type": "Rice Plate",
        "rating": 4.5,
        "price": 60,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "riceplate.jpeg", 
        "landmark": "Maa Vaishino Devi Dham",
        "veg": True,
        "otheroptions": ["Various types of Indian Food"]
    },

    {   "name": "Talbidkar Vada Pav",
        "location": "https://maps.app.goo.gl/xufVJebaDxTq44jg6",
        "hotelname": "Talbidkar vadawale",
        "type": "Vada Pav",
        "rating": 4.5,
        "price": 18,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "wadapaav.jpeg", 
        "landmark": "Maa Vaishino Devi Dham",
        "veg": True,
        "otheroptions": ["Various types of Vada Pav"]
    },

    {   "name": "Kokate Vada Pav",
        "location": "https://maps.app.goo.gl/t3yaXpqNzf2jpPSdA",
        "hotelname": "Kokate vada pav",
        "type": "Vada Pav",
        "rating": 4.5,
        "price": 18,
        "quantity": 1,
        "time": "All Day",
        "imageurl": "kokate.jpg", 
        "landmark": "Near Akurdi Raiway station",
        "veg": True,
        "otheroptions": ["Various types of Vada Pav"]
    }
]

# Insert food data into MongoDB
food_collection.insert_many(food_data)
print("Food data inserted successfully!")
